### PR TITLE
 Fixing the issue for redirect for smaller screen when clicking on navbar

### LINKED ISSUE #940: redirected to home page when clicked on navbar in smaller resolutions
**Describe the bug**
Currently, when clicked on navbar in smaller screen resolutions (such as mobile device), we get redirected to the landing page `/`.

**To Reproduce**
1. Go to the `signin` page (for example).
2. Click on the `navbar` in smaller screen resolution devices
3. You will get redirected to the landing page `/`

**Expected behaviour**
You should not get redirected to the landing page if clicked on navbar in small screen sizes.

**Screenshots**
mobile

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by abhu-A-J**
closes #940 

Kindly review the same. :smile:

### CODE REVIEW

File: src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts [hunk 1]
```diff
@@ -35,6 +35,7 @@ export const Navigation = styled.nav<NavigationProps>`
 export const NavigationBarBrand = styled(Link)`
   /* padding: 1rem; */
```
Comment (Dishebh) [inline src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts:36]: While you are at it, can you remove the comment as well?

Comment (abhu-A-J) [reply src/ignitus-Shared/ignitus-DesignSystem/ignitus-Organisms/ignitus-Navigation/styles.ts]: Sure thing! :+1:

**Review by Dishebh — APPROVED** [review]
